import streamlit as st
import google.generativeai as genai
from dotenv import load_dotenv
from langchain_community.document_loaders import PyPDFLoader
import os
from io import BytesIO
from docx import Document

# ==========================================
# 1. 核心网络代理配置 (针对 v2rayN 10809 端口)
# ==========================================
proxy = 'http://127.0.0.1:10809' 
os.environ.update({
    'http_proxy': proxy, 
    'https_proxy': proxy, 
    'HTTP_PROXY': proxy, 
    'HTTPS_PROXY': proxy,
    'GRPC_PROXY_EXPAND': '1'
})

# ==========================================
# 2. 环境与状态初始化
# ==========================================
load_dotenv()
st.set_page_config(page_title="Academic Shrimp | 学术虾", page_icon="🦐", layout="wide")

# 初始化 Session State (这是解决“报告消失”的关键)
if "full_report" not in st.session_state:
    st.session_state.full_report = ""  # 存储生成的综述
if "all_context" not in st.session_state:
    st.session_state.all_context = ""  # 存储抽取的文本供问答使用

genai.configure(api_key=os.getenv("GOOGLE_API_KEY"), transport='grpc')
MODEL_NAME = 'gemini-2.5-flash'
model = genai.GenerativeModel(MODEL_NAME)

# Word 生成函数
from docx.shared import RGBColor, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

def generate_docx(content):
    doc = Document()
    
    # 1. 设置主标题 (居中, 深蓝色)
    header = doc.add_heading('Academic Shrimp | 学术综述报告', 0)
    header.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for run in header.runs:
        run.font.color.rgb = RGBColor(0, 51, 102) # 深蓝色
        run.font.name = 'Arial'

    # 2. 添加生成时间和免责声明
    import datetime
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    run = p.add_run(f"报告生成时间: {timestamp}")
    run.font.size = Pt(9)
    run.italic = True

    # 3. 处理正文内容
    # 识别常见的维度标题并加粗美化
    sections = [
        "【核心摘要】", "【创新点】", "【创新点分析】", 
        "【方法论评价】", "【学术洞察】", "【审稿意见】"
    ]

    for line in content.split('\n'):
        line = line.strip()
        if not line:
            continue
            
        # 匹配标题行
        is_section = any(s in line for s in sections)
        
        if is_section:
            # 添加一个小间距
            doc.add_paragraph()
            p = doc.add_paragraph()
            run = p.add_run(line)
            run.bold = True
            run.font.size = Pt(14)
            run.font.color.rgb = RGBColor(204, 0, 0) # 虾红色 (配合项目名)
        elif line.startswith('论文题目：') or line.startswith('作者：'):
            p = doc.add_paragraph()
            run = p.add_run(line)
            run.bold = True
        else:
            # 普通段落
            p = doc.add_paragraph(line)
            p.paragraph_format.line_spacing = 1.5 # 设置 1.5 倍行间距，学术范儿

    # 4. 页脚
    section = doc.sections[0]
    footer = section.footer
    footer.paragraphs[0].text = "Generated by Academic Shrimp AI v1.0 | 2026 Hackathon Prototype"
    footer.paragraphs[0].alignment = WD_ALIGN_PARAGRAPH.CENTER

    # 保存二进制流
    bio = BytesIO()
    doc.save(bio)
    return bio.getvalue()

# ==========================================
# 3. 界面设计
# ==========================================
st.title("🦐 Academic Shrimp (Native Mode)")
st.markdown("---")

with st.sidebar:
    st.header("📂 论文上传中心")
    uploaded_files = st.file_uploader("选择 PDF 论文", type="pdf", accept_multiple_files=True)
    st.info(f"驱动引擎: {MODEL_NAME}\n\n策略: DASS 头尾采样")
    if st.button("🗑️ 清空当前对话"):
        st.session_state.full_report = ""
        st.session_state.all_context = ""
        st.rerun()

# ==========================================
# 4. 核心逻辑：跑分析
# ==========================================
if st.button("🚀 让虾干活！"):
    if uploaded_files:
        try:
            # 链路检查
            model.generate_content("Hi", request_options={"timeout": 15})
            
            all_text_for_summary = ""
            all_text_full = "" # 留作深度问答使用
            
            with st.spinner("🦐 虾正在执行 DASS 采样分析 (前3页 + 后2页)..."):
                for uploaded_file in uploaded_files:
                    with open("temp.pdf", "wb") as f:
                        f.write(uploaded_file.getbuffer())
                    
                    loader = PyPDFLoader("temp.pdf")
                    pages = loader.load()
                    
                    # 综述采样逻辑
                    sampled = pages[:3] + pages[-2:] if len(pages) > 5 else pages
                    all_text_for_summary += "\n".join([p.page_content for p in sampled])
                    # 全量保存用于后续追问 (Gemini 2.5 容量够大)
                    all_text_full += "\n".join([p.page_content for p in pages])

            st.session_state.all_context = all_text_full # 存入状态

            # 生成综述报告
            st.markdown("### 📝 虾的学术分析报告")
            placeholder = st.empty()
            temp_report = ""
            
            prompt = f"你是一位资深审稿人，请根据提供的文献采样内容进行【核心摘要】、【创新点】、【方法论评价】、【学术洞察】深度分析：\n\n{all_text_for_summary}"
            
            response = model.generate_content(prompt, stream=True, request_options={"timeout": 600})
            
            for chunk in response:
                if chunk.text:
                    temp_report += chunk.text
                    placeholder.markdown(temp_report + "▌")
            
            placeholder.markdown(temp_report)
            st.session_state.full_report = temp_report # 存入状态，保证刷新不丢失
            st.balloons()
            
        except Exception as e:
            st.error(f"❌ 运行失败: {e}")
    else:
        st.warning("请先上传 PDF 文件！")

# ==========================================
# 5. 持久化显示报告与深度提问 (支持多轮对话)
# ==========================================
if st.session_state.full_report:
    # 5.1 渲染主报告
    st.markdown("### 📝 虾的学术分析报告")
    st.markdown(st.session_state.full_report)

    # 下载按钮
    docx_data = generate_docx(st.session_state.full_report)
    st.download_button(
        label="📥 下载 Word 报告",
        data=docx_data,
        file_name="Academic_Shrimp_Report.docx",
        mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    )

    st.markdown("---")
    st.subheader("💬 针对论文细节深度追问")

    # --- 新增：初始化对话历史 ---
    if "messages" not in st.session_state:
        st.session_state.messages = []

    # --- 新增：渲染之前的对话记录 ---
    for message in st.session_state.messages:
        with st.chat_message(message["role"]):
            st.markdown(message["content"])

    # --- 新增：处理新提问 ---
    user_query = st.chat_input("询问论文细节...")
    
    if user_query:
        # 1. 展示并保存用户问题
        st.session_state.messages.append({"role": "user", "content": user_query})
        with st.chat_message("user"):
            st.markdown(user_query)
        
        # 2. 生成、展示并保存 AI 回答
        with st.chat_message("assistant"):
            with st.spinner("虾正在查阅全文..."):
                qa_prompt = f"背景内容：{st.session_state.all_context}\n\n问题：{user_query}"
                try:
                    qa_res = model.generate_content(qa_prompt)
                    answer = qa_res.text
                    st.markdown(answer)
                    st.session_state.messages.append({"role": "assistant", "content": answer})
                except Exception as e:
                    st.error(f"问答出错: {e}")

st.markdown("---")
st.caption("Academic Shrimp v1.0 | Hackathon Prototype 2026")